[package]
name = "rubhub"
version = "0.1.0"
edition = "2024"
license = "EUPL-1.2"
default-run = "rubhub"

[[bin]]
name = "rubhub"
path = "src/main.rs"

[[bin]]
name = "dummy-to-cache-dependencies"
path = "dummy.rs"

[dependencies]
anyhow = "1"
axum = { version = "0.8", features = ["ws", "multipart"] }
askama = "0.12"
dotenvy = "0.15"
gix = { version = "0.75", default-features = false, features = ["basic"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
russh = "0.55"
argon2 = { version = "0.5", features = ["password-hash"] }
time = { version = "0.3", features = ["serde", "macros", "formatting", "parsing"] }
tokio = { version = "1.48", features = ["macros", "process", "signal"] }
tower = "0.5"
tower-cookies = "0.11"
tower-http = { version = "0.6", features = ["fs"] }
urlencoding = "2.1"
uuid = { version = "1", features = ["serde", "v4", "v7"] }
sea-orm = { version = "1.1", features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros", "with-time" ] }
markdown = "1"
ammonia = "4.1"
rust-embed = "8.9"
mime_guess = "2.0"
