[package]
name = "rubhub"
version = "0.1.0"
edition = "2024"
license = "EUPL-1.2"
default-run = "rubhub"

[[bin]]
name = "rubhub"
path = "src/main.rs"

[[bin]]
name = "dummy-to-cache-dependencies"
path = "dummy.rs"

[dependencies]
rubhub-auth-store = { path = "auth_store" }

anyhow = "1"
axum = { version = "0.8", features = ["ws", "multipart"] }
askama = "0.15"
dotenvy = "0.15"
gix = { version = "0.77", default-features = false, features = ["basic", "tree-editor"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
smallvec = "1"
russh = "0.56"
argon2 = { version = "0.5", features = ["password-hash"] }
time = { version = "0.3", features = ["serde", "macros", "formatting", "parsing"] }
tokio = { version = "1.48", features = ["macros", "process", "signal", "rt-multi-thread", "rt"] }
futures = "0.3"
tower = "0.5"
tower-cookies = "0.11"
tower-http = { version = "0.6", features = ["fs", "set-header"] }
urlencoding = "2.1"
uuid = { version = "1", features = ["serde", "v4", "v7"] }
markdown = "1"
ammonia = "4.1"
sd-notify = "0.4"
rust-embed = "8.9"
mime_guess = "2.0"
sha2 = "0.10"
serde_urlencoded = "0.7"
tower_governor = "0.8"
validator = "0.20"

[dev-dependencies]
tempfile = "3"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "cookies"] }
