#!/usr/bin/env bash
rsync -avhze ssh ./ --exclude={'/.direnv','/.claude','/.env','/.git','/data','/node_modules','/target','/dist'} --delete rubhub:~/src/rubhub
ssh rubhub 'cd src/rubhub && ./deploy.systemd'
