#!/usr/bin/env bash
rsync -avhe ssh ./ --exclude '.env' --exclude '.git' --exclude 'data' --exclude 'node_modules' --exclude 'target' rubhub:~/src/rubhub
ssh rubhub 'DOCKER_BUILDKIT=1 cd src/rubhub && docker compose up -d --build'