version: "3.8"

services:
  rubhub:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HTTP_BIND_ADDRESS: 127.0.0.1
      HTTP_BIND_PORT: 3000
      SSH_BIND_ADDRESS: 0.0.0.0
      SSH_PORT: 22
      SSH_PUBLIC_HOST: rubhub.net
      DIR_ROOT: /app/data/
    volumes:
      - ./data:/app/data
    deploy:
      replicas: 2
    network_mode: host

volumes:
  rubhub-data:
  pgdata:
